// Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

#include<bits/stdc++.h>
using namespace std;
typedef long long ll;

set<string> store;
void printSubsequence(string ans, int low, int high, string s)
{
	if (low == high)
		store.insert(ans);
	else
	{
		printSubsequence(ans, low + 1, high, s);
		ans = ans + s[low];
		printSubsequence(ans, low + 1, high, s);
	}
}

int main()
{
	int test;
	cin >> test;
	while (test--)
	{
		string s;
		cin >> s;
		//code
		printSubsequence("", 0, s.length(), s);
		set<string>::iterator itr;
		for (itr = store.begin(); itr != store.end(); ++itr)
		{
			cout << *itr << "\n";
		}
		store.clear();
	}
	return 0;
}